# Generated by Django 5.1.1 on 2024-10-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='tag',
            field=models.CharField(default='Store', max_length=100),
        ),
    ]
