# Generated by Django 5.1.1 on 2024-10-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_wallet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-20T00:00:00'),
            preserve_default=False,
        ),
    ]
