# Generated by Django 5.1.1 on 2024-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_wallet_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='tag',
            field=models.CharField(default='Watchlist', max_length=100),
        ),
    ]
